### ISSUE TITLE
工程报错.

### ISSUE THREAD

**Issue by vicwing** [maoruibin/GankDaily#12]
我用的AndroidStudio2.0 beta5,打开报错了.
AAPT err(Facade for 1870252414): libpng error: Not a PNG file
Error:Execution failed for task ':app:mergeFirDebugResources'.

> Some file crunching failed, see logs for details,什么问题 ?

**Comment by maoruibin** [comment]
现在解决了吗？你看下你的gradle 用的是本地设置的路径还是 在线获取的

**Comment by lorryhou** [comment]
是图片格式问题，某张图片可能并不是png格式。

**Comment by maoruibin** [comment]
可以帮我解一下吗 解完 PR 即可

**Comment by maoruibin** [comment]
现在应该已经好了~
