### ISSUE TITLE
2个Bug，1个优化点

### ISSUE THREAD

**Issue by zhp075366** [maoruibin/GankDaily#17]
Bug1：妹子页面下拉有时完全没反应，需要向上滑动后再下拉才有反应。
Bug2：大部分点妹子进行大图查看时（第一次点，这时还没缓存大图），UI会有闪动，而且整个大图没居中会在左上角。

Function1：希望增加进大图查看妹子时，能左右滑动。

希望大神能解决，谢谢！

**Comment by maoruibin** [comment]
试试新的客户端 https://fir.im/gankdaily
